#%RAML 1.0 Trait
usage: Apply this trait to enforce client id identification

headers:
      client_id:
        type: string
        description: client secret to auntheicate system API
        required: true
      client_secret:
        type: string
        description: client secret to authenticate system API
        required: true
  