http:
  port: "8081"
  

database:
  uhub:
    host: "oracle-69965-0.cloudclusters.net"
    port: "10757"
    user: "uhubdevuser"
    password: "![vsWiIT1rsoZsAzC/vZZOzA==]"
    instance: "XE"