#%RAML 1.0 Trait
usage: Apply this trait to enable API consumer to send their own correlation id for tracking end to end transaction. Mule will use its own transaction-id header but consumer can correlate their own correlation-id to mule transaction-id 
headers:
    x-correlation-id:
        type: string
        required: false
        description: Correlation ID to maintain over APIs